"""empty message

Revision ID: 1832297eab8f
Revises: 42b8181d9a1b
Create Date: 2022-01-25 22:11:42.568906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1832297eab8f'
down_revision = '42b8181d9a1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('added_by', sa.Integer(), server_default='4', nullable=True))
    op.create_foreign_key(None, 'categories', 'user', ['added_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_column('categories', 'added_by')
    # ### end Alembic commands ###
