"""empty message

Revision ID: 4001f406e5b3
Revises: fd45c7677b98
Create Date: 2022-01-25 22:09:18.305766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4001f406e5b3'
down_revision = 'fd45c7677b98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('status', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'status')
    # ### end Alembic commands ###
