"""empty message

Revision ID: 42b8181d9a1b
Revises: c139e0626527
Create Date: 2022-01-25 22:11:33.081631

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '42b8181d9a1b'
down_revision = 'c139e0626527'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('categories_ibfk_1', 'categories', type_='foreignkey')
    op.drop_column('categories', 'added_by')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('added_by', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('categories_ibfk_1', 'categories', 'user', ['added_by'], ['id'])
    # ### end Alembic commands ###
