"""empty message

Revision ID: 4b00873b39ad
Revises: 5ced2b13aadf
Create Date: 2022-01-25 21:50:33.749389

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4b00873b39ad'
down_revision = '5ced2b13aadf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('added_by', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'articles', 'user', ['added_by'], ['id'])
    op.alter_column('user', 'last_name',
               existing_type=mysql.VARCHAR(length=75),
               nullable=False)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=70),
               nullable=False)
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=150),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=150),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=70),
               nullable=True)
    op.alter_column('user', 'last_name',
               existing_type=mysql.VARCHAR(length=75),
               nullable=True)
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_column('articles', 'added_by')
    # ### end Alembic commands ###
