"""empty message

Revision ID: 5ced2b13aadf
Revises: 87c9723b308d
Create Date: 2022-01-23 19:11:57.925675

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5ced2b13aadf'
down_revision = '87c9723b308d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'name',
               existing_type=mysql.VARCHAR(length=75),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'name',
               existing_type=mysql.VARCHAR(length=75),
               nullable=True)
    # ### end Alembic commands ###
