"""empty message

Revision ID: 7933e62ce6e6
Revises: f982c7285730
Create Date: 2022-01-25 22:08:22.701431

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7933e62ce6e6'
down_revision = 'f982c7285730'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('status', mysql.VARCHAR(length=10), nullable=False))
    # ### end Alembic commands ###
