"""empty message

Revision ID: 85dd7574d1ad
Revises: 14509771c4f3
Create Date: 2022-01-22 21:39:50.836880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85dd7574d1ad'
down_revision = '14509771c4f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('status', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'status')
    # ### end Alembic commands ###
