"""empty message

Revision ID: 8d077d83ca5c
Revises: 4b00873b39ad
Create Date: 2022-01-25 21:55:18.979327

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8d077d83ca5c'
down_revision = '4b00873b39ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'added_by',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'categories', 'user', ['added_by'], ['id'])
    op.add_column('user', sa.Column('phone_number', sa.String(length=10), nullable=True))
    op.alter_column('user', 'last_name',
               existing_type=mysql.VARCHAR(length=75),
               nullable=False)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=70),
               nullable=False)
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=150),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=150),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=70),
               nullable=True)
    op.alter_column('user', 'last_name',
               existing_type=mysql.VARCHAR(length=75),
               nullable=True)
    op.drop_column('user', 'phone_number')
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.alter_column('categories', 'added_by',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
