"""empty message

Revision ID: 9e58d6057004
Revises: c59a7c6b1703
Create Date: 2022-01-25 22:01:09.014276

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9e58d6057004'
down_revision = 'c59a7c6b1703'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'added_by',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'added_by',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
